version: '3.1'
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - docker-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "9002:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./.docker/pgadmin:/root/.pgadmin
    restart: always

volumes:
  docker-postgres:
    external: true
